name: Update Readme Workflow
on:
  schedule:
    # Update daily at 3AM
    - cron: '0 3 * * *'
  # Also update on manual runs
  workflow_dispatch:

jobs:
  update-template:
    name: Update Readme using Template Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add GitHub Age
        uses: teoxoy/profile-readme-stats@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add GitHub Activity Stats
        uses: actions-js/profile-readme@v1
        with:
          username: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Repo
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  update-waka:
    name: Update Readme with Waka Data
    needs: update-template
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TIME: false
