name: Update with Waka Stats
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with statistics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TIME: false
